# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Python pip
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    directory: "/"
    # Ignore updates for the Django package with versions 5
    ignore:
      - dependency-name: "django"
        versions: ["5.*"]
    # Check for updates once a week
    schedule:
      interval: "weekly"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
